/*
 * SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define STORAGE_T %in_out_t_storage%
#define TYPE_IN_OUT %in_out_t_type%

#define COMP_T %in_out_t_comp%

layout(local_size_x = %warpX%) in;

layout(push_constant) uniform PushConstants {
    uint axis;
    uint nanMode;
} pushConstants;

layout(constant_id = 0) const uint32_t RANK = RANK_MAX;

layout(set = 0, binding = 0) uniform tensorARM<STORAGE_T, RANK> outputData;
layout(set = 1, binding = 0) uniform tensorARM<STORAGE_T, RANK> inputData;

void main() {
    uint[RANK] index;
    getIndex(outputData, index);

    const uint dim = index[pushConstants.axis];
    COMP_T result = COMP_T(%init%);

    uint[RANK] inputShape;
    getShape(inputShape, inputData);

    for (uint i = 0; i < inputShape[pushConstants.axis]; i++) {
        index[pushConstants.axis] = i;

        STORAGE_T rawValue;
        tensorReadARM(inputData, index, rawValue);
        COMP_T value = DECODE_STORAGE_TO_COMP(rawValue, TYPE_IN_OUT, COMP_T);

#if (IS_FLOAT(TYPE_IN_OUT) || IS_REDUCED_FLOAT(TYPE_IN_OUT))
        if (isnan(value)) {
            if (pushConstants.nanMode == NAN_MODE_IGNORE) {
                // Ignore value and continue
                continue;
            }
            if (pushConstants.nanMode == NAN_MODE_PROPAGATE) {
                // If any value is NaN, then the result must be NaN
                result = value;
                break;
            }
        }
#endif

        result = %operation%;
    }

    index[pushConstants.axis] = dim;

#if IS_REDUCED_FLOAT(TYPE_IN_OUT)
    tensorWriteARM(outputData, index, ENCODE_COMP_TO_STORAGE(result, STORAGE_T, TYPE_IN_OUT));
#else
    tensorWriteARM(outputData, index, STORAGE_T(result));
#endif
}
