/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#version 450
precision highp float;
precision highp sampler2D;
precision mediump image2D;

// Local Work Size set as Specialization Constants
layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z = 1) in;

layout(constant_id = 2) const float INPUT_FLOW_SCALE = 1.f;
layout(constant_id = 3) const int OUTPUT_SIZE_X = 960;
layout(constant_id = 4) const int OUTPUT_SIZE_Y = 540;

layout (binding = 0) uniform highp sampler2D imageSampler;
layout (binding = 1) uniform highp sampler2D flowImageSampler;

layout (set=0, binding = 2, r8) uniform writeonly image2D dst_img;

// We expect flow is positive forward flow from dst to src,
// while anet and tfa "expects the negative forward flow from output image to source image"
float sample_bilinear(sampler2D sampler_value, vec2 sample_pos)
{
    precise vec2 texel_pos = sample_pos - 0.5f;
    ivec2 base = ivec2(floor(texel_pos));
    precise vec2 fraction = texel_pos - vec2(base);
    ivec2 max_pos = textureSize(sampler_value, 0) - 1;

    float p00 = texelFetch(sampler_value, clamp(base, ivec2(0), max_pos), 0).x;
    float p10 = texelFetch(sampler_value, clamp(base + ivec2(1, 0), ivec2(0), max_pos), 0).x;
    float p01 = texelFetch(sampler_value, clamp(base + ivec2(0, 1), ivec2(0), max_pos), 0).x;
    float p11 = texelFetch(sampler_value, clamp(base + ivec2(1, 1), ivec2(0), max_pos), 0).x;

    precise float row0 = p00 + (p10 - p00) * fraction.x;
    precise float row1 = p01 + (p11 - p01) * fraction.x;
    precise float value = row0 + (row1 - row0) * fraction.y;
    return value;
}

float calc_dense_warp(vec2 flow, ivec2 pos)
{
    precise vec2 src_pos = vec2(pos) + 0.5f + flow;
    return sample_bilinear(imageSampler, src_pos);
}

void main()
{
    const ivec2 pos = ivec2(gl_GlobalInvocationID.x,
                            gl_GlobalInvocationID.y);
    if (any(greaterThanEqual(pos, ivec2(OUTPUT_SIZE_X, OUTPUT_SIZE_Y)))) return;

    vec2 flow = texelFetch(flowImageSampler, pos, 0).xy;
    flow *= INPUT_FLOW_SCALE;
    float warped = calc_dense_warp(flow, pos);
    uint warped_unorm8 = uint(clamp(floor(warped * 255.f + 0.5f), 0.f, 255.f));
    imageStore(dst_img, pos, vec4(float(warped_unorm8) / 255.f, 0, 0, 0));
}
