/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#version 450
precision highp float;
precision mediump sampler2D;
precision mediump image2D;
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

// Local Work Size set as Specialization Constants
layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z = 1) in;

layout(constant_id = 2) const float INPUT_FLOW_SCALE = 1.f;
layout(constant_id = 3) const int OUTPUT_SIZE_X = 960;
layout(constant_id = 4) const int OUTPUT_SIZE_Y = 540;

layout (binding = 0) uniform mediump sampler2D imageSampler;
layout (binding = 1) uniform highp sampler2D flowImageSampler;

layout (set=0, binding = 2, r8) uniform writeonly image2D dst_img;

// We expect flow is positive forward flow from dst to src,
// while anet and tfa "expects the negative forward flow from output image to source image"
float16_t calc_dense_warp(vec2 flow, ivec2 pos)
{
    vec2 src_pos = vec2(pos) + 0.5f + flow;
    return float16_t(texture(imageSampler, src_pos).x);
}

void main()
{
    const ivec2 pos = ivec2(gl_GlobalInvocationID.x,
                            gl_GlobalInvocationID.y);
    if (any(greaterThanEqual(pos, ivec2(OUTPUT_SIZE_X, OUTPUT_SIZE_Y)))) return;

    vec2 flow = texelFetch(flowImageSampler, pos, 0).xy;
    flow *= INPUT_FLOW_SCALE;
    float16_t warped = calc_dense_warp(flow, pos);
    imageStore(dst_img, pos, vec4(warped, 0, 0, 0));
}
