/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#version 450
precision highp float;
precision mediump sampler2D;
precision highp image2D;
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

// Local Work Size set as Specialization Constants
layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z = 1) in;

layout(constant_id = 2) const bool PAD_X = true;
layout(constant_id = 3) const bool PAD_Y = true;
layout(constant_id = 4) const int OUTPUT_SIZE_X = 960;
layout(constant_id = 5) const int OUTPUT_SIZE_Y = 540;

layout (binding = 0) uniform sampler2D imageSampler;

layout (set = 0, binding = 1, r8) uniform writeonly image2D dst_img;

float16_t calc_blur_and_bilinear_fused_4samples(vec2 src_pos) {
    // By taking advantage of linear interporaltion by GPU sampler,
    // 4x4 filter is computed by 4 bilinear samplings from 2x2 pixels each
    // The sampling location (+-0.75) is calculated from coefficient values, which is H(1,3,3,1) * V(1,3,3,1)
    float sum = 0.f;
    sum += float(texture(imageSampler, src_pos + vec2(-0.75f, -0.75f)).x);
    sum += float(texture(imageSampler, src_pos + vec2(+0.75f, -0.75f)).x);
    sum += float(texture(imageSampler, src_pos + vec2(-0.75f, +0.75f)).x);
    sum += float(texture(imageSampler, src_pos + vec2(+0.75f, +0.75f)).x);
    return float16_t(sum * 0.25f);
}

void main()
{
    const ivec2 pos = ivec2(gl_GlobalInvocationID.x,
                            gl_GlobalInvocationID.y);
    if (any(greaterThanEqual(pos, ivec2(OUTPUT_SIZE_X, OUTPUT_SIZE_Y)))) return;

    vec2 scale = vec2(2.f);
    ivec2 edge_wo_pad = ivec2(PAD_X ? OUTPUT_SIZE_X - 2 : OUTPUT_SIZE_X - 1,
                              PAD_Y ? OUTPUT_SIZE_Y - 2 : OUTPUT_SIZE_Y - 1);

    // In computing pixels on the edge, we could rely on CLAM_TO_EDGE addressing,
    // however we follow the reference implementation strictly to mitigate difference.
    // In case the src resolution is not exactly multiple of the dst resolution,
    // i.e. PAD_X, PAD_Y is true,
    // The below casing results in replicating values of right and bottom edges
    vec2 dst_pos = vec2(min(pos, edge_wo_pad));

    vec2 uv = (dst_pos + 0.5f) * scale;
    float16_t downsampled = calc_blur_and_bilinear_fused_4samples(uv);
    imageStore(dst_img, pos, vec4(min(downsampled, 1.HF), 0, 0, 0));
}
