/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#version 450
precision highp float;
precision highp sampler2D;
precision highp image2D;

// Local Work Size set as Specialization Constants
layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z = 1) in;

layout(constant_id = 2) const bool PAD_X = true;
layout(constant_id = 3) const bool PAD_Y = true;
layout(constant_id = 4) const int OUTPUT_SIZE_X = 960;
layout(constant_id = 5) const int OUTPUT_SIZE_Y = 540;

layout (binding = 0) uniform sampler2D imageSampler;

layout (set = 0, binding = 1, r8) uniform writeonly image2D dst_img;

uint load_unorm8(ivec2 pos)
{
    pos = clamp(pos, ivec2(0), textureSize(imageSampler, 0) - 1);
    return uint(floor(texelFetch(imageSampler, pos, 0).x * 255.f + 0.5f));
}

uint calc_blur(ivec2 base_pos)
{
    const uint weights[4] = {1u, 3u, 3u, 1u};
    uint sum = 0u;
    for (int y = 0; y < 4; ++y) {
        for (int x = 0; x < 4; ++x) {
            sum += weights[x] * weights[y] * load_unorm8(base_pos + ivec2(x, y));
        }
    }
    return (sum + 32u) / 64u;
}

void main()
{
    const ivec2 pos = ivec2(gl_GlobalInvocationID.x,
                            gl_GlobalInvocationID.y);
    if (any(greaterThanEqual(pos, ivec2(OUTPUT_SIZE_X, OUTPUT_SIZE_Y)))) return;

    ivec2 edge_wo_pad = ivec2(PAD_X ? OUTPUT_SIZE_X - 2 : OUTPUT_SIZE_X - 1,
                              PAD_Y ? OUTPUT_SIZE_Y - 2 : OUTPUT_SIZE_Y - 1);

    // In computing pixels on the edge, we could rely on CLAMP_TO_EDGE addressing,
    // however we follow the reference implementation strictly to mitigate difference.
    // In case the src resolution is not exactly multiple of the dst resolution,
    // i.e. PAD_X, PAD_Y is true,
    // The below casing results in replicating values of right and bottom edges
    ivec2 dst_pos = min(pos, edge_wo_pad);
    uint downsampled = calc_blur(dst_pos * 2 - 1);
    imageStore(dst_img, pos, vec4(float(downsampled) / 255.f, 0, 0, 0));
}
