/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#version 450
precision highp float;
precision highp sampler2D;
precision mediump image2D;
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_16bit_storage : require

// Local Work Size set as Specialization Constants
layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z = 1) in;

layout(constant_id = 2) const float OUTPUT_FLOW_SCALE = 1.f;
layout(constant_id = 3) const int OUTPUT_SIZE_X = 480;
layout(constant_id = 4) const int OUTPUT_SIZE_Y = 270;

layout (binding = 0) uniform highp sampler2D imageSampler;

layout (set=0, binding = 1, rg16f) uniform writeonly image2D dst_img;


/** Sorts element-wise two vectors.
 */
#define sort(a, b) \
    { \
        f16vec2 min_val = min(a, b); \
        f16vec2 max_val = max(a, b); \
        a = min_val; \
        b = max_val; \
    }

/*
    Sorting network to sort 9 vectors of 2 elements and return their median.
 */
f16vec2 sort9(f16vec2 p0, f16vec2 p1, f16vec2 p2, f16vec2 p3, f16vec2 p4, f16vec2 p5, f16vec2 p6, f16vec2 p7, f16vec2 p8)
{
    sort(p1, p2);
    sort(p4, p5);
    sort(p7, p8);
    sort(p0, p1);
    sort(p3, p4);
    sort(p6, p7);
    sort(p1, p2);
    sort(p4, p5);
    sort(p7, p8);
    sort(p0, p3);
    sort(p5, p8);
    sort(p4, p7);
    sort(p3, p6);
    sort(p1, p4);
    sort(p2, p5);
    sort(p4, p7);
    sort(p4, p2);
    sort(p6, p4);
    sort(p4, p2);

    return p4;
}

f16vec2 load_clamp_edge(ivec2 pos)
{
    ivec2 size = textureSize(imageSampler, 0);
    return f16vec2(texelFetch(imageSampler, clamp(pos, ivec2(0), size - 1), 0).xy);
}

f16vec2 calc(ivec2 pos)
{
    f16vec2 filtered = sort9(load_clamp_edge(pos + ivec2(-1, -1)),
                             load_clamp_edge(pos + ivec2( 0, -1)),
                             load_clamp_edge(pos + ivec2( 1, -1)),
                             load_clamp_edge(pos + ivec2(-1,  0)),
                             load_clamp_edge(pos),
                             load_clamp_edge(pos + ivec2( 1,  0)),
                             load_clamp_edge(pos + ivec2(-1,  1)),
                             load_clamp_edge(pos + ivec2( 0,  1)),
                             load_clamp_edge(pos + ivec2( 1,  1)));
    return filtered * f16vec2(OUTPUT_FLOW_SCALE);
}


void main()
{
    const ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(pos, ivec2(OUTPUT_SIZE_X, OUTPUT_SIZE_Y)))) return;

    imageStore(dst_img, pos, f16vec4(calc(pos), 0, 0));
}
