/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#version 450
precision highp float;
precision highp sampler2D;
precision mediump image2D;
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_8bit_storage : require

// Local Work Size set as Specialization Constants
layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z = 1) in;

layout(constant_id = 2) const float SCALE_X = 0.5f;  // The ratio of src/dst, used to scale the magnitude of flow
layout(constant_id = 3) const float SCALE_Y = 0.5f;  // The ratio of src/dst, used to scale the magnitude of flow
layout(constant_id = 4) const float INV_SCALE_X = 2.f;  // The ratio of dst/src, used for upsampling
layout(constant_id = 5) const float INV_SCALE_Y = 2.f;  // The ratio of dst/src, used for upsampling
layout(constant_id = 6) const int OUTPUT_SIZE_X = 480;
layout(constant_id = 7) const int OUTPUT_SIZE_Y = 270;
layout(constant_id = 8) const uint STRIDE_DST = 480;   // The number of elements in a row (x-axis) including padding
layout(constant_id = 9) const uint STRIDE_DST_FLOW = 480;   // The number of elements in a row (x-axis) including padding

layout (binding = 0) uniform highp sampler2D imageSampler;
layout (binding = 1) uniform highp sampler2D flowImageSampler;

layout (set = 0, binding = 2, std430) buffer _dst_buf_u8{
    uint8_t dst_buf_u8[];
};

layout (set = 0, binding = 3, std430) buffer _dst_flow_buf{
    f16vec2 dst_flow_buf[];
};

vec4 sample_bilinear(sampler2D sampler_value, vec2 sample_pos)
{
    precise vec2 texel_pos = sample_pos - 0.5f;
    ivec2 base = ivec2(floor(texel_pos));
    precise vec2 fraction = texel_pos - vec2(base);
    ivec2 max_pos = textureSize(sampler_value, 0) - 1;

    vec4 p00 = texelFetch(sampler_value, clamp(base, ivec2(0), max_pos), 0);
    vec4 p10 = texelFetch(sampler_value, clamp(base + ivec2(1, 0), ivec2(0), max_pos), 0);
    vec4 p01 = texelFetch(sampler_value, clamp(base + ivec2(0, 1), ivec2(0), max_pos), 0);
    vec4 p11 = texelFetch(sampler_value, clamp(base + ivec2(1, 1), ivec2(0), max_pos), 0);

    precise vec4 row0 = p00 + (p10 - p00) * fraction.x;
    precise vec4 row1 = p01 + (p11 - p01) * fraction.x;
    precise vec4 value = row0 + (row1 - row0) * fraction.y;
    return value;
}

vec2 calc_mv_process(vec2 src_pos)
{
    precise vec2 flow = sample_bilinear(flowImageSampler, src_pos).xy;
    flow *= vec2(SCALE_X, SCALE_Y);
    return flow;
}

// We expect flow is positive forward flow from dst to src,
// while anet and tfa "expects the negative forward flow from output image to source image"
float calc_dense_warp(vec2 flow, ivec2 pos)
{
    precise vec2 src_pos = vec2(pos) + 0.5f + flow;
    return sample_bilinear(imageSampler, src_pos).x;
}

uint8_t convert_uint8(float x)
{
    return uint8_t(clamp(floor(x * 255.f + 0.5f), 0.f, 255.f));
}

void main()
{
    const ivec2 pos = ivec2(gl_GlobalInvocationID.x,
                            gl_GlobalInvocationID.y);
    if (any(greaterThanEqual(pos, ivec2(OUTPUT_SIZE_X, OUTPUT_SIZE_Y)))) return;

    vec2 inv_scale = vec2(INV_SCALE_X, INV_SCALE_Y);
    vec2 uv = (vec2(pos) + 0.5f) * inv_scale;
    vec2 flow = calc_mv_process(uv);
    float warped = calc_dense_warp(flow, pos);

    uint8_t dst_val = convert_uint8(warped);
    uint index = STRIDE_DST * pos.y + pos.x;
    dst_buf_u8[index] = dst_val;
    dst_flow_buf[STRIDE_DST_FLOW * pos.y + pos.x] = f16vec2(flow);
}
