/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#version 450
precision highp float;
precision mediump sampler2D;
precision mediump image2D;
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_16bit_storage : require

#ifndef OUTPUT_COST
#error OUTPUT_COST must be defined
#endif

// Local Work Size set as Specialization Constants
layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z = 1) in;

layout(constant_id = 2) const int OUTPUT_SIZE_X = 480;
layout(constant_id = 3) const int OUTPUT_SIZE_Y = 270;

layout (binding = 0) uniform mediump sampler2D mvInputSampler;
layout (binding = 1) uniform mediump sampler2D flowBlockMatchSampler;

layout (binding = 2) uniform usampler2D costAtInputMvSampler;
layout (binding = 3) uniform usampler2D minCostBlockMatchSampler;
layout (set=0, binding=4, rg16f) uniform writeonly image2D dst_flow_img;
#if OUTPUT_COST
layout (set=0, binding=5, r16ui) uniform writeonly uimage2D dst_cost_img;
#endif

void replace_flow(ivec2 pos, uint16_t cost_at_input_mv, uint16_t min_cost_block_match,
                  out f16vec2 flow_out, out uint16_t cost_out)
{
    // Read MV and flow
    f16vec2 mv_input         = f16vec2(texelFetch(mvInputSampler, pos, 0).xy);
    f16vec2 flow_block_match = f16vec2(texelFetch(flowBlockMatchSampler, pos, 0).xy);

    // Select by comparing cost
    bool min_is_mv = cost_at_input_mv < min_cost_block_match;
    flow_out = min_is_mv ? mv_input : flow_block_match;
    cost_out = min_is_mv ? cost_at_input_mv : min_cost_block_match;
}

void main()
{
    const ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(pos, ivec2(OUTPUT_SIZE_X, OUTPUT_SIZE_Y)))) return;

    const uint16_t cost_at_input_mv = uint16_t(texelFetch(costAtInputMvSampler, pos, 0).x);
    const uint16_t min_cost_block_match = uint16_t(texelFetch(minCostBlockMatchSampler, pos, 0).x);

    f16vec2 flow;
    uint16_t cost;
    replace_flow(pos, cost_at_input_mv, min_cost_block_match, flow, cost);

    imageStore(dst_flow_img, pos, f16vec4(flow, 0, 0));
#if OUTPUT_COST
    imageStore(dst_cost_img, pos, u16vec4(cost, 0, 0, 0));
#endif
}
