/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#version 450
precision highp float;  // 32bit precision is necessary for det_A
precision highp sampler2D;
precision mediump image2D;
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_8bit_storage : require

#define MACRO_BLOCK (5)
#define BLOCK_R (MACRO_BLOCK / 2)

#ifndef DO_ACCUMULATE
#error DO_ACCUMULATE must be defined
#endif

// Local Work Size set as Specialization Constants
layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z = 1) in;

layout(constant_id = 2) const int OUTPUT_SIZE_X = 480;
layout(constant_id = 3) const int OUTPUT_SIZE_Y = 270;
layout(constant_id = 4) const uint STRIDE_INT_FLOW = 480;   // The number of elements in a row (x-axis) including padding
layout(constant_id = 5) const uint STRIDE_PREV_FLOW = 480;

layout (set = 0, binding = 0) uniform highp sampler2D imageSearchSampler;

layout (set = 0, binding = 1) uniform highp sampler2D imageTemplateSampler;

layout (set = 0, binding = 2, std430) buffer _int_flow_buf{
    i8vec2 int_flow_buf[];
};

#if DO_ACCUMULATE
layout (set = 0, binding = 3, std430) buffer _prev_flow_buf{
    f16vec2 prev_flow_buf[];
};
#endif

layout (set = 0, binding = 4, rg16f) uniform writeonly image2D dst_flow_img;

const ivec2 output_size = ivec2(OUTPUT_SIZE_X, OUTPUT_SIZE_Y);

bool is_outside(ivec2 pos)
{
    return pos.x < 0 || pos.x >= output_size.x || pos.y < 0 || pos.y >= output_size.y;
}

float16_t load_clamp_edge(sampler2D sampler_value, ivec2 pos)
{
    ivec2 size = textureSize(sampler_value, 0);
    return float16_t(texelFetch(sampler_value, clamp(pos, ivec2(0), size - 1), 0).x);
}

float16_t load_zero(sampler2D sampler_value, ivec2 pos)
{
    ivec2 size = textureSize(sampler_value, 0);
    if (any(lessThan(pos, ivec2(0))) || any(greaterThanEqual(pos, size))) {
        return 0.HF;
    }
    return float16_t(texelFetch(sampler_value, pos, 0).x);
}

void calc_gradient(ivec2 pos, out float16_t dfx, out float16_t dfy, out float16_t f)
{
    // Compute gradient on the fly
    {
        precise float16_t f_m1 = load_clamp_edge(imageTemplateSampler, pos + ivec2(-1, 0));
        f                      = load_clamp_edge(imageTemplateSampler, pos);
        precise float16_t f_p1 = load_clamp_edge(imageTemplateSampler, pos + ivec2(+1, 0));
        dfx = (f_p1 - f_m1) * 0.5HF;
    }
    {
        precise float16_t f_m1 = load_clamp_edge(imageTemplateSampler, pos + ivec2(0, -1));
        precise float16_t f_p1 = load_clamp_edge(imageTemplateSampler, pos + ivec2(0, +1));
        dfy = (f_p1 - f_m1) * 0.5HF;
    }

    // Zero padding in case pos is outside
    // NOTE: CLAMP_TO_EDGE sampler is used to read f to compute gradient
    float16_t is_inside = is_outside(pos) ? 0.HF : 1.HF;
    f   = f   * is_inside;
    dfx = dfx * is_inside;
    dfy = dfy * is_inside;
}

f16vec2 calc(const ivec2 pos)
{
    precise float16_t a = 0.HF, b = 0.HF, d = 0.HF, p = 0.HF, q = 0.HF;
    ivec2 int_flow = ivec2(int_flow_buf[STRIDE_INT_FLOW * pos.y + pos.x]);

    // Read inputs and accumulate value, which updates:
    //   - a, b, d, p, q
    #define acc_work(_bx, _by) \
    { \
        ivec2 bpos = pos + ivec2(_bx, _by); \
        precise float16_t f, dfx, dfy; \
        calc_gradient(bpos, dfx, dfy, f); \
        a += dfx * dfx; \
        b += dfx * dfy; \
        d += dfy * dfy; \
        ivec2 g_pos = bpos + int_flow; \
        precise float16_t g = load_zero(imageSearchSampler, g_pos); \
        precise float16_t z = g - f;\
        p += z * dfx; \
        q += z * dfy; \
    }

    /*
        5x5 Reduction with predicate, where 0 means we don't accumulate
        1, 1, 1, 1, 1,
        1, 0, 0, 0, 1,
        1, 0, 0, 0, 1,
        1, 0, 0, 0, 1,
        1, 1, 1, 1, 1
    */
    // Top edge, loop for x
    for (int bx = -BLOCK_R; bx <= BLOCK_R; ++bx) {
        acc_work(bx, -BLOCK_R);
    }
    // Middle rows, loop for y
    for (int by = -BLOCK_R + 1; by <= BLOCK_R - 1; ++by) {
        acc_work(-BLOCK_R, by);  // Left edge
        acc_work( BLOCK_R, by);  // Right edge
    }
    // Bottom edge, loop for x
    for (int bx = -BLOCK_R; bx <= BLOCK_R; ++bx) {
        acc_work(bx, BLOCK_R);
    }

    // Use 32 bit float for numeric error sensitive process
    precise float det_A = float(a) * float(d) - float(b) * float(b);
    precise vec2 numerator;
    numerator.x = float(d) * float(p) - float(b) * float(q);
    numerator.y = float(a) * float(q) - float(b) * float(p);

    vec2 subpixel = vec2(0.f);
    if (det_A > 1e-7f) {
        subpixel = numerator / det_A;
        subpixel = mix(subpixel, vec2(0.f), greaterThanEqual(abs(subpixel), vec2(1.f)));
    }

    // Add integer flow here to save memory bandwidth
    // Also accumulate the flow from previous level
    // NOTE: The reference implementaion returns negated integer flow, but Motin Engine doesn't.
    f16vec2 out_flow = f16vec2(int_flow) - f16vec2(subpixel);

    #if DO_ACCUMULATE
        out_flow += prev_flow_buf[STRIDE_PREV_FLOW * pos.y + pos.x];
    #endif

    return out_flow;
}


void main()
{
    const ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(pos, output_size))) return;

    f16vec2 flow = calc(pos);

    imageStore(dst_flow_img, pos, f16vec4(flow, 0, 0));
}
