#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
# Import the TOSA 1.0.2 datatype tables into the offline shader build.
#
# Input: tosa.xml from arm/tosa-specification tag v1.0.2.
# https://github.com/arm/tosa-specification/blob/v1.0.2/tosa.xml
# No network access is needed by the build.
# RESCALE's additional choices follow its Operation Function in the specification.
import argparse
import itertools
import xml.etree.ElementTree as ET
from pathlib import Path


def generate(source):
    text = source.read_text()
    root = ET.fromstring(text[text.index("<?xml") :])
    version = root.find("version")
    if tuple(version.get(k) for k in ("major", "minor", "patch")) != ("1", "0", "2"):
        raise ValueError("Expected the TOSA 1.0.2 specification")
    lines = [
        "# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>",
        "# SPDX-License-" + "Identifier: Apache-2.0",
        "#",
        "# Generated by scripts/update_tosa_shader_types.py from TOSA 1.0.2 tosa.xml.",
        "# https://www.mlplatform.org/tosa/tosa_spec_1_0_2.html",
        "# Source: https://github.com/arm/tosa-specification/blob/v1.0.2/tosa.xml",
        "# All profiles/extensions are included. Rows retain TOSA types; shader storage",
        "# widens i4 to i8 and i48 to i64. Native packed i4 tensors are not implemented.",
        "# Integer SINT/UINT bindings share unsigned tensor interfaces; arithmetic",
        "# remains signed except for RESCALE's explicit unsigned attributes.",
        "# Shapes, rounding, padding, etc. are specialization/push constants, not",
        "# additional GLSL variants. Compilation does not establish TOSA conformance.",
        "",
    ]
    for operator in root.findall("./operators/operatorgroup/operator"):
        name = operator.findtext("name")
        lines.append(f"# {name}")
        for support in operator.findall("typesupport"):
            types = {
                k: v
                for k, v in support.attrib.items()
                if k not in ("mode", "version_added")
            }
            profiles = "+".join(p.get("name") for p in support.findall("op_profile"))
            # SPIR-V requires both extensions for BF16 <-> FP8 CASTs.
            # https://github.khronos.org/SPIRV-Registry/extended/TOSA.001000.1.html#_cast
            if name == "CAST" and "bf16_t" in types.values():
                for fp8, extension in (
                    ("fp8e4m3_t", "EXT-FP8E4M3"),
                    ("fp8e5m2_t", "EXT-FP8E5M2"),
                ):
                    if fp8 in types.values():
                        profiles = "EXT-BF16+" + extension
            variants = [types]
            if name == "RESCALE":
                variants = []
                for scale32, unsigned_input, unsigned_output in itertools.product(
                    (False, True), repeat=3
                ):
                    in_type, out_type = types["in_t"], types["out_t"]
                    if (scale32 and in_type == "i48_t") or (
                        unsigned_input and unsigned_output
                    ):
                        continue
                    if unsigned_input and (
                        in_type not in ("i8_t", "i16_t") or out_type == "i32_t"
                    ):
                        continue
                    if unsigned_output and (
                        out_type not in ("i8_t", "i16_t")
                        or in_type in ("i32_t", "i48_t")
                    ):
                        continue
                    variants.append(
                        dict(
                            in_t="u" + in_type if unsigned_input else in_type,
                            out_t="u" + out_type if unsigned_output else out_type,
                            mul_t="i32_t" if scale32 else "i16_t",
                        )
                    )
            for variant in variants:
                args = " ".join(f"{k}={v}" for k, v in variant.items())
                suffix = f" {args}" if args else ""
                lines.append(f'mlel_tosa_variant({name} "{profiles}"{suffix})')
        lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Import TOSA 1.0.2 datatype tables into the offline shader build."
    )
    parser.add_argument("specification", type=Path)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "graph/shaders/tosa_1_0_types.cmake",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate(args.specification)
    if args.check:
        if args.output.read_text() != result:
            parser.error(f"{args.output} differs from the TOSA datatype tables")
    else:
        args.output.write_text(result)


if __name__ == "__main__":
    main()
