# SPDX-FileCopyrightText: Copyright 2025-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#

macro(mlel_arithmetic_type_info TYPE OUTPUT)
    if("${TYPE}" STREQUAL "bool")
        set(${OUTPUT}_LOWEST "0")
        set(${OUTPUT}_MAX "1")
        set(${OUTPUT}_TYPE "0x6231")
        set(${OUTPUT}_COMP "${TYPE}")
    elseif("${TYPE}" STREQUAL "uint8_t")
        set(${OUTPUT}_LOWEST "0u")
        set(${OUTPUT}_MAX "255u")
        set(${OUTPUT}_TYPE "0x7531")
        set(${OUTPUT}_COMP "${TYPE}")
    elseif("${TYPE}" STREQUAL "int8_t")
        set(${OUTPUT}_LOWEST "-128")
        set(${OUTPUT}_MAX "127")
        set(${OUTPUT}_TYPE "0x6931")
        set(${OUTPUT}_COMP "${TYPE}")
    elseif("${TYPE}" STREQUAL "uint16_t")
        set(${OUTPUT}_LOWEST "0u")
        set(${OUTPUT}_MAX "65535u")
        set(${OUTPUT}_TYPE "0x7532")
        set(${OUTPUT}_COMP "${TYPE}")
    elseif("${TYPE}" STREQUAL "int16_t")
        set(${OUTPUT}_LOWEST "-32768")
        set(${OUTPUT}_MAX "32767")
        set(${OUTPUT}_TYPE "0x6932")
        set(${OUTPUT}_COMP "${TYPE}")
    elseif("${TYPE}" STREQUAL "uint64_t")
        set(${OUTPUT}_LOWEST "0ul")
        set(${OUTPUT}_MAX "18446744073709551615ul")
        set(${OUTPUT}_TYPE "0x7538")
        set(${OUTPUT}_COMP "${TYPE}")
    elseif("${TYPE}" STREQUAL "int64_t")
        set(${OUTPUT}_LOWEST "(-9223372036854775807L - 1L)")
        set(${OUTPUT}_MAX "9223372036854775807L")
        set(${OUTPUT}_TYPE "0x6938")
        set(${OUTPUT}_COMP "${TYPE}")
    elseif("${TYPE}" STREQUAL "uint32_t")
        set(${OUTPUT}_LOWEST "0u")
        set(${OUTPUT}_MAX "4294967295u")
        set(${OUTPUT}_TYPE "0x7534")
        set(${OUTPUT}_COMP "${TYPE}")
    elseif("${TYPE}" STREQUAL "int")
        set(${OUTPUT}_LOWEST "-2147483648")
        set(${OUTPUT}_MAX "2147483647")
        set(${OUTPUT}_TYPE "0x6934")
        set(${OUTPUT}_COMP "${TYPE}")
    elseif("${TYPE}" STREQUAL "bfloat16_t")
        set(${OUTPUT}_LOWEST "-3.402823466e+38")
        set(${OUTPUT}_MAX "3.402823466e+38")
        set(${OUTPUT}_TYPE "0x6642")
        set(${OUTPUT}_COMP "float")
    elseif("${TYPE}" STREQUAL "float8_e5m2_t")
        set(${OUTPUT}_LOWEST "-57344")
        set(${OUTPUT}_MAX "57344")
        set(${OUTPUT}_TYPE "0x664D")
        set(${OUTPUT}_COMP "float16_t")
    elseif("${TYPE}" STREQUAL "float8_e4m3_t")
        set(${OUTPUT}_LOWEST "-448")
        set(${OUTPUT}_MAX "448")
        set(${OUTPUT}_TYPE "0x664E")
        set(${OUTPUT}_COMP "float16_t")
    elseif("${TYPE}" STREQUAL "float16_t")
        set(${OUTPUT}_LOWEST "-65504")
        set(${OUTPUT}_MAX "65504")
        set(${OUTPUT}_TYPE "0x6632")
        set(${OUTPUT}_COMP "${TYPE}")
    elseif("${TYPE}" STREQUAL "float")
        set(${OUTPUT}_LOWEST "-3.402823466e+38")
        set(${OUTPUT}_MAX "3.402823466e+38")
        set(${OUTPUT}_TYPE "0x6634")
        set(${OUTPUT}_COMP "${TYPE}")
    elseif("${TYPE}" STREQUAL "double")
        set(${OUTPUT}_LOWEST "-1.7976931348623158e+308")
        set(${OUTPUT}_MAX "1.7976931348623158e+308")
        set(${OUTPUT}_TYPE "0x6638")
        set(${OUTPUT}_COMP "${TYPE}")
    endif()
endmacro()

# Precompiled variants are keyed by arithmetic types. Integer tensor interfaces
# use unsigned declarations so each variant accepts either SINT or UINT storage.
# Keep this choice separate from numeric limits, type tags, and computation types,
# matching getTensorInterfaceGlslType in common/utils.cpp.
function(mlel_tensor_interface_type SCALAR_TYPE OUTPUT)
    if(SCALAR_TYPE MATCHES "^(u?int8_t)$")
        set(TENSOR_TYPE "uint8_t")
    elseif(SCALAR_TYPE MATCHES "^(u?int16_t)$")
        set(TENSOR_TYPE "uint16_t")
    elseif(SCALAR_TYPE MATCHES "^(u?int|u?int32_t)$")
        set(TENSOR_TYPE "uint32_t")
    elseif(SCALAR_TYPE MATCHES "^(u?int64_t)$")
        set(TENSOR_TYPE "uint64_t")
    else()
        set(TENSOR_TYPE "${SCALAR_TYPE}")
    endif()
    set(${OUTPUT} "${TENSOR_TYPE}" PARENT_SCOPE)
endfunction()

# Compile list of arguments, removing the first three
math(EXPR COUNT "${CMAKE_ARGC} - 1")
foreach(i RANGE 3 ${COUNT})
    list(APPEND ARGV "${CMAKE_ARGV${i}}")
endforeach()

# Parse command line arguments
cmake_parse_arguments(ARGS "" "INPUT_FILE;OUTPUT_FILE;GLSLANG" "REPLACE" ${ARGV})

# Read source file into memory
file(READ ${ARGS_INPUT_FILE} GLSL)

foreach(R ${ARGS_REPLACE})
    string(REGEX MATCH "^([^=]+)=(.*)$" R ${R})
    set(KEY ${CMAKE_MATCH_1})
    set(VAL ${CMAKE_MATCH_2})
    string(REPLACE "\\ " " " VAL ${VAL})

    mlel_arithmetic_type_info(${VAL} ${KEY})

    mlel_tensor_interface_type("${VAL}" TENSOR_TYPE)
    string(REPLACE "%${KEY}_storage%" "${TENSOR_TYPE}" GLSL "${GLSL}")

    string(REPLACE "%${KEY}%" "${VAL}" GLSL "${GLSL}")
    string(REPLACE "%${KEY}_lowest%" "${${KEY}_LOWEST}" GLSL "${GLSL}")
    string(REPLACE "%${KEY}_max%" "${${KEY}_MAX}" GLSL "${GLSL}")
    string(REPLACE "%${KEY}_type%" "${${KEY}_TYPE}" GLSL "${GLSL}")
    string(REPLACE "%${KEY}_comp%" "${${KEY}_COMP}" GLSL "${GLSL}")
endforeach()

file(WRITE ${ARGS_OUTPUT_FILE}.comp "${GLSL}")

set(GLSLANG_FLAGS -V --target-env vulkan1.3)
if(USE_FLOAT_AS_DOUBLE)
    list(APPEND GLSLANG_FLAGS "-DUSE_FLOAT_AS_DOUBLE=ON")
endif()

execute_process(
    COMMAND ${ARGS_GLSLANG} ${GLSLANG_FLAGS} -o ${ARGS_OUTPUT_FILE} ${ARGS_OUTPUT_FILE}.comp
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    COMMAND_ERROR_IS_FATAL ANY
)
