# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#
# Generated by scripts/update_tosa_shader_types.py from TOSA 1.0.2 tosa.xml.
# https://www.mlplatform.org/tosa/tosa_spec_1_0_2.html
# Source: https://github.com/arm/tosa-specification/blob/v1.0.2/tosa.xml
# All profiles/extensions are included. Rows retain TOSA types; shader storage
# widens i4 to i8 and i48 to i64. Native packed i4 tensors are not implemented.
# Integer SINT/UINT bindings share unsigned tensor interfaces; arithmetic
# remains signed except for RESCALE's explicit unsigned attributes.
# Shapes, rounding, padding, etc. are specialization/push constants, not
# additional GLSL variants. Compilation does not establish TOSA conformance.

# ARGMAX
mlel_tosa_variant(ARGMAX "PRO-INT" in_t=i8_t out_t=i32_t)
mlel_tosa_variant(ARGMAX "EXT-INT16" in_t=i16_t out_t=i32_t)
mlel_tosa_variant(ARGMAX "EXT-FP8E4M3" in_t=fp8e4m3_t out_t=i32_t)
mlel_tosa_variant(ARGMAX "EXT-FP8E5M2" in_t=fp8e5m2_t out_t=i32_t)
mlel_tosa_variant(ARGMAX "PRO-FP" in_t=fp16_t out_t=i32_t)
mlel_tosa_variant(ARGMAX "EXT-BF16" in_t=bf16_t out_t=i32_t)
mlel_tosa_variant(ARGMAX "PRO-FP" in_t=fp32_t out_t=i32_t)

# AVG_POOL2D
mlel_tosa_variant(AVG_POOL2D "PRO-INT" in_out_t=i8_t acc_t=i32_t)
mlel_tosa_variant(AVG_POOL2D "EXT-INT16" in_out_t=i16_t acc_t=i32_t)
mlel_tosa_variant(AVG_POOL2D "EXT-FP8E4M3" in_out_t=fp8e4m3_t acc_t=fp16_t)
mlel_tosa_variant(AVG_POOL2D "EXT-FP8E5M2" in_out_t=fp8e5m2_t acc_t=fp16_t)
mlel_tosa_variant(AVG_POOL2D "PRO-FP" in_out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(AVG_POOL2D "PRO-FP" in_out_t=fp16_t acc_t=fp32_t)
mlel_tosa_variant(AVG_POOL2D "EXT-BF16" in_out_t=bf16_t acc_t=fp32_t)
mlel_tosa_variant(AVG_POOL2D "PRO-FP" in_out_t=fp32_t acc_t=fp32_t)

# CONV2D
mlel_tosa_variant(CONV2D "PRO-INT" in_t=i8_t weight_t=i8_t out_t=i32_t acc_t=i32_t)
mlel_tosa_variant(CONV2D "EXT-INT4" in_t=i8_t weight_t=i4_t out_t=i32_t acc_t=i32_t)
mlel_tosa_variant(CONV2D "EXT-INT16" in_t=i16_t weight_t=i8_t out_t=i48_t acc_t=i48_t)
mlel_tosa_variant(CONV2D "EXT-FP8E4M3" in_t=fp8e4m3_t weight_t=fp8e4m3_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(CONV2D "EXT-FP8E5M2" in_t=fp8e5m2_t weight_t=fp8e5m2_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(CONV2D "PRO-FP" in_t=fp16_t weight_t=fp16_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(CONV2D "PRO-FP" in_t=fp16_t weight_t=fp16_t out_t=fp16_t acc_t=fp32_t)
mlel_tosa_variant(CONV2D "EXT-BF16" in_t=bf16_t weight_t=bf16_t out_t=bf16_t acc_t=fp32_t)
mlel_tosa_variant(CONV2D "PRO-FP" in_t=fp32_t weight_t=fp32_t out_t=fp32_t acc_t=fp32_t)

# CONV3D
mlel_tosa_variant(CONV3D "PRO-INT" in_t=i8_t weight_t=i8_t out_t=i32_t acc_t=i32_t)
mlel_tosa_variant(CONV3D "EXT-INT4" in_t=i8_t weight_t=i4_t out_t=i32_t acc_t=i32_t)
mlel_tosa_variant(CONV3D "EXT-INT16" in_t=i16_t weight_t=i8_t out_t=i48_t acc_t=i48_t)
mlel_tosa_variant(CONV3D "EXT-FP8E4M3" in_t=fp8e4m3_t weight_t=fp8e4m3_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(CONV3D "EXT-FP8E5M2" in_t=fp8e5m2_t weight_t=fp8e5m2_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(CONV3D "PRO-FP" in_t=fp16_t weight_t=fp16_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(CONV3D "PRO-FP" in_t=fp16_t weight_t=fp16_t out_t=fp16_t acc_t=fp32_t)
mlel_tosa_variant(CONV3D "EXT-BF16" in_t=bf16_t weight_t=bf16_t out_t=bf16_t acc_t=fp32_t)
mlel_tosa_variant(CONV3D "PRO-FP" in_t=fp32_t weight_t=fp32_t out_t=fp32_t acc_t=fp32_t)

# DEPTHWISE_CONV2D
mlel_tosa_variant(DEPTHWISE_CONV2D "PRO-INT" in_t=i8_t weight_t=i8_t out_t=i32_t acc_t=i32_t)
mlel_tosa_variant(DEPTHWISE_CONV2D "EXT-INT4" in_t=i8_t weight_t=i4_t out_t=i32_t acc_t=i32_t)
mlel_tosa_variant(DEPTHWISE_CONV2D "EXT-INT16" in_t=i16_t weight_t=i8_t out_t=i48_t acc_t=i48_t)
mlel_tosa_variant(DEPTHWISE_CONV2D "EXT-FP8E4M3" in_t=fp8e4m3_t weight_t=fp8e4m3_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(DEPTHWISE_CONV2D "EXT-FP8E5M2" in_t=fp8e5m2_t weight_t=fp8e5m2_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(DEPTHWISE_CONV2D "PRO-FP" in_t=fp16_t weight_t=fp16_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(DEPTHWISE_CONV2D "PRO-FP" in_t=fp16_t weight_t=fp16_t out_t=fp16_t acc_t=fp32_t)
mlel_tosa_variant(DEPTHWISE_CONV2D "EXT-BF16" in_t=bf16_t weight_t=bf16_t out_t=bf16_t acc_t=fp32_t)
mlel_tosa_variant(DEPTHWISE_CONV2D "PRO-FP" in_t=fp32_t weight_t=fp32_t out_t=fp32_t acc_t=fp32_t)

# FFT2D
mlel_tosa_variant(FFT2D "EXT-FFT" in_out_t=fp32_t)

# MATMUL
mlel_tosa_variant(MATMUL "PRO-INT" in_t=i8_t out_t=i32_t)
mlel_tosa_variant(MATMUL "EXT-INT16" in_t=i16_t out_t=i48_t)
mlel_tosa_variant(MATMUL "EXT-FP8E4M3" in_t=fp8e4m3_t out_t=fp16_t)
mlel_tosa_variant(MATMUL "EXT-FP8E5M2" in_t=fp8e5m2_t out_t=fp16_t)
mlel_tosa_variant(MATMUL "PRO-FP" in_t=fp16_t out_t=fp16_t)
mlel_tosa_variant(MATMUL "PRO-FP" in_t=fp16_t out_t=fp32_t)
mlel_tosa_variant(MATMUL "EXT-BF16" in_t=bf16_t out_t=fp32_t)
mlel_tosa_variant(MATMUL "PRO-FP" in_t=fp32_t out_t=fp32_t)

# MAX_POOL2D
mlel_tosa_variant(MAX_POOL2D "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(MAX_POOL2D "EXT-INT16" in_out_t=i16_t)
mlel_tosa_variant(MAX_POOL2D "EXT-FP8E4M3" in_out_t=fp8e4m3_t)
mlel_tosa_variant(MAX_POOL2D "EXT-FP8E5M2" in_out_t=fp8e5m2_t)
mlel_tosa_variant(MAX_POOL2D "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(MAX_POOL2D "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(MAX_POOL2D "PRO-FP" in_out_t=fp32_t)

# RFFT2D
mlel_tosa_variant(RFFT2D "EXT-FFT" in_out_t=fp32_t)

# TRANSPOSE_CONV2D
mlel_tosa_variant(TRANSPOSE_CONV2D "PRO-INT" in_t=i8_t weight_t=i8_t out_t=i32_t acc_t=i32_t)
mlel_tosa_variant(TRANSPOSE_CONV2D "EXT-INT4" in_t=i8_t weight_t=i4_t out_t=i32_t acc_t=i32_t)
mlel_tosa_variant(TRANSPOSE_CONV2D "EXT-INT16" in_t=i16_t weight_t=i8_t out_t=i48_t acc_t=i48_t)
mlel_tosa_variant(TRANSPOSE_CONV2D "EXT-FP8E4M3" in_t=fp8e4m3_t weight_t=fp8e4m3_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(TRANSPOSE_CONV2D "EXT-FP8E5M2" in_t=fp8e5m2_t weight_t=fp8e5m2_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(TRANSPOSE_CONV2D "PRO-FP" in_t=fp16_t weight_t=fp16_t out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(TRANSPOSE_CONV2D "PRO-FP" in_t=fp16_t weight_t=fp16_t out_t=fp16_t acc_t=fp32_t)
mlel_tosa_variant(TRANSPOSE_CONV2D "EXT-BF16" in_t=bf16_t weight_t=bf16_t out_t=bf16_t acc_t=fp32_t)
mlel_tosa_variant(TRANSPOSE_CONV2D "PRO-FP" in_t=fp32_t weight_t=fp32_t out_t=fp32_t acc_t=fp32_t)

# CLAMP
mlel_tosa_variant(CLAMP "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(CLAMP "EXT-INT16" in_out_t=i16_t)
mlel_tosa_variant(CLAMP "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(CLAMP "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(CLAMP "PRO-FP" in_out_t=fp32_t)

# ERF
mlel_tosa_variant(ERF "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(ERF "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(ERF "PRO-FP" in_out_t=fp32_t)

# SIGMOID
mlel_tosa_variant(SIGMOID "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(SIGMOID "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(SIGMOID "PRO-FP" in_out_t=fp32_t)

# TANH
mlel_tosa_variant(TANH "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(TANH "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(TANH "PRO-FP" in_out_t=fp32_t)

# ADD
mlel_tosa_variant(ADD "PRO-INT+PRO-FP" in_out_t=i32_t)
mlel_tosa_variant(ADD "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(ADD "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(ADD "PRO-FP" in_out_t=fp32_t)

# ARITHMETIC_RIGHT_SHIFT
mlel_tosa_variant(ARITHMETIC_RIGHT_SHIFT "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(ARITHMETIC_RIGHT_SHIFT "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(ARITHMETIC_RIGHT_SHIFT "PRO-INT" in_out_t=i32_t)

# BITWISE_AND
mlel_tosa_variant(BITWISE_AND "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(BITWISE_AND "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(BITWISE_AND "PRO-INT" in_out_t=i32_t)

# BITWISE_OR
mlel_tosa_variant(BITWISE_OR "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(BITWISE_OR "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(BITWISE_OR "PRO-INT" in_out_t=i32_t)

# BITWISE_XOR
mlel_tosa_variant(BITWISE_XOR "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(BITWISE_XOR "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(BITWISE_XOR "PRO-INT" in_out_t=i32_t)

# INTDIV
mlel_tosa_variant(INTDIV "PRO-INT+PRO-FP" in_out_t=i32_t)

# LOGICAL_AND
mlel_tosa_variant(LOGICAL_AND "PRO-INT+PRO-FP" in_out_t=bool_t)

# LOGICAL_LEFT_SHIFT
mlel_tosa_variant(LOGICAL_LEFT_SHIFT "PRO-INT+PRO-FP" in_out_t=i8_t)
mlel_tosa_variant(LOGICAL_LEFT_SHIFT "PRO-INT+PRO-FP" in_out_t=i16_t)
mlel_tosa_variant(LOGICAL_LEFT_SHIFT "PRO-INT+PRO-FP" in_out_t=i32_t)

# LOGICAL_RIGHT_SHIFT
mlel_tosa_variant(LOGICAL_RIGHT_SHIFT "PRO-INT+PRO-FP" in_out_t=i8_t)
mlel_tosa_variant(LOGICAL_RIGHT_SHIFT "PRO-INT+PRO-FP" in_out_t=i16_t)
mlel_tosa_variant(LOGICAL_RIGHT_SHIFT "PRO-INT+PRO-FP" in_out_t=i32_t)

# LOGICAL_OR
mlel_tosa_variant(LOGICAL_OR "PRO-INT+PRO-FP" in_out_t=bool_t)

# LOGICAL_XOR
mlel_tosa_variant(LOGICAL_XOR "PRO-INT+PRO-FP" in_out_t=bool_t)

# MAXIMUM
mlel_tosa_variant(MAXIMUM "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(MAXIMUM "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(MAXIMUM "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(MAXIMUM "PRO-FP" in_out_t=fp32_t)

# MINIMUM
mlel_tosa_variant(MINIMUM "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(MINIMUM "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(MINIMUM "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(MINIMUM "PRO-FP" in_out_t=fp32_t)

# MUL
mlel_tosa_variant(MUL "PRO-INT" in_t=i8_t out_t=i32_t)
mlel_tosa_variant(MUL "PRO-INT" in_t=i16_t out_t=i32_t)
mlel_tosa_variant(MUL "PRO-INT+PRO-FP" in_t=i32_t out_t=i32_t)
mlel_tosa_variant(MUL "PRO-FP" in_t=fp16_t out_t=fp16_t)
mlel_tosa_variant(MUL "EXT-BF16" in_t=bf16_t out_t=bf16_t)
mlel_tosa_variant(MUL "PRO-FP" in_t=fp32_t out_t=fp32_t)

# POW
mlel_tosa_variant(POW "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(POW "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(POW "PRO-FP" in_out_t=fp32_t)

# SUB
mlel_tosa_variant(SUB "PRO-INT+PRO-FP" in_out_t=i32_t)
mlel_tosa_variant(SUB "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(SUB "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(SUB "PRO-FP" in_out_t=fp32_t)

# TABLE
mlel_tosa_variant(TABLE "PRO-INT" in_t=i8_t table_t=i8_t TABLE_SIZE=256 out_t=i8_t)
mlel_tosa_variant(TABLE "EXT-INT16" in_t=i16_t table_t=i16_t TABLE_SIZE=513 out_t=i32_t)

# ABS
mlel_tosa_variant(ABS "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(ABS "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(ABS "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(ABS "PRO-FP" in_out_t=fp32_t)

# BITWISE_NOT
mlel_tosa_variant(BITWISE_NOT "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(BITWISE_NOT "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(BITWISE_NOT "PRO-INT" in_out_t=i32_t)

# CEIL
mlel_tosa_variant(CEIL "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(CEIL "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(CEIL "PRO-FP" in_out_t=fp32_t)

# CLZ
mlel_tosa_variant(CLZ "PRO-INT" in_out_t=i32_t)

# COS
mlel_tosa_variant(COS "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(COS "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(COS "PRO-FP" in_out_t=fp32_t)

# EXP
mlel_tosa_variant(EXP "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(EXP "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(EXP "PRO-FP" in_out_t=fp32_t)

# FLOOR
mlel_tosa_variant(FLOOR "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(FLOOR "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(FLOOR "PRO-FP" in_out_t=fp32_t)

# LOG
mlel_tosa_variant(LOG "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(LOG "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(LOG "PRO-FP" in_out_t=fp32_t)

# LOGICAL_NOT
mlel_tosa_variant(LOGICAL_NOT "PRO-INT+PRO-FP" in_out_t=bool_t)

# NEGATE
mlel_tosa_variant(NEGATE "PRO-INT" in_out_t=i8_t acc_t=i32_t)
mlel_tosa_variant(NEGATE "PRO-INT" in_out_t=i16_t acc_t=i32_t)
mlel_tosa_variant(NEGATE "PRO-INT" in_out_t=i32_t acc_t=i32_t)
mlel_tosa_variant(NEGATE "PRO-FP" in_out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(NEGATE "EXT-BF16" in_out_t=bf16_t acc_t=bf16_t)
mlel_tosa_variant(NEGATE "PRO-FP" in_out_t=fp32_t acc_t=fp32_t)

# RECIPROCAL
mlel_tosa_variant(RECIPROCAL "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(RECIPROCAL "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(RECIPROCAL "PRO-FP" in_out_t=fp32_t)

# RSQRT
mlel_tosa_variant(RSQRT "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(RSQRT "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(RSQRT "PRO-FP" in_out_t=fp32_t)

# SIN
mlel_tosa_variant(SIN "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(SIN "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(SIN "PRO-FP" in_out_t=fp32_t)

# SELECT
mlel_tosa_variant(SELECT "PRO-INT+PRO-FP" in_out_t=bool_t)
mlel_tosa_variant(SELECT "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(SELECT "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(SELECT "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(SELECT "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(SELECT "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(SELECT "PRO-FP" in_out_t=fp32_t)

# EQUAL
mlel_tosa_variant(EQUAL "PRO-INT" in_t=i32_t out_t=bool_t)
mlel_tosa_variant(EQUAL "PRO-FP" in_t=fp16_t out_t=bool_t)
mlel_tosa_variant(EQUAL "EXT-BF16" in_t=bf16_t out_t=bool_t)
mlel_tosa_variant(EQUAL "PRO-FP" in_t=fp32_t out_t=bool_t)

# GREATER
mlel_tosa_variant(GREATER "PRO-INT" in_t=i32_t out_t=bool_t)
mlel_tosa_variant(GREATER "PRO-FP" in_t=fp16_t out_t=bool_t)
mlel_tosa_variant(GREATER "EXT-BF16" in_t=bf16_t out_t=bool_t)
mlel_tosa_variant(GREATER "PRO-FP" in_t=fp32_t out_t=bool_t)

# GREATER_EQUAL
mlel_tosa_variant(GREATER_EQUAL "PRO-INT" in_t=i32_t out_t=bool_t)
mlel_tosa_variant(GREATER_EQUAL "PRO-FP" in_t=fp16_t out_t=bool_t)
mlel_tosa_variant(GREATER_EQUAL "EXT-BF16" in_t=bf16_t out_t=bool_t)
mlel_tosa_variant(GREATER_EQUAL "PRO-FP" in_t=fp32_t out_t=bool_t)

# REDUCE_ALL
mlel_tosa_variant(REDUCE_ALL "PRO-INT+PRO-FP" in_out_t=bool_t)

# REDUCE_ANY
mlel_tosa_variant(REDUCE_ANY "PRO-INT+PRO-FP" in_out_t=bool_t)

# REDUCE_MAX
mlel_tosa_variant(REDUCE_MAX "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(REDUCE_MAX "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(REDUCE_MAX "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(REDUCE_MAX "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(REDUCE_MAX "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(REDUCE_MAX "PRO-FP" in_out_t=fp32_t)

# REDUCE_MIN
mlel_tosa_variant(REDUCE_MIN "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(REDUCE_MIN "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(REDUCE_MIN "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(REDUCE_MIN "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(REDUCE_MIN "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(REDUCE_MIN "PRO-FP" in_out_t=fp32_t)

# REDUCE_PRODUCT
mlel_tosa_variant(REDUCE_PRODUCT "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(REDUCE_PRODUCT "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(REDUCE_PRODUCT "PRO-FP" in_out_t=fp32_t)

# REDUCE_SUM
mlel_tosa_variant(REDUCE_SUM "PRO-INT" in_out_t=i32_t acc_t=i32_t)
mlel_tosa_variant(REDUCE_SUM "PRO-FP" in_out_t=fp16_t acc_t=fp16_t)
mlel_tosa_variant(REDUCE_SUM "EXT-BF16" in_out_t=bf16_t acc_t=fp32_t)
mlel_tosa_variant(REDUCE_SUM "PRO-FP" in_out_t=fp32_t acc_t=fp32_t)

# CONCAT
mlel_tosa_variant(CONCAT "PRO-INT+PRO-FP" in_out_t=bool_t)
mlel_tosa_variant(CONCAT "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(CONCAT "EXT-INT16" in_out_t=i16_t)
mlel_tosa_variant(CONCAT "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(CONCAT "EXT-FP8E4M3" in_out_t=fp8e4m3_t)
mlel_tosa_variant(CONCAT "EXT-FP8E5M2" in_out_t=fp8e5m2_t)
mlel_tosa_variant(CONCAT "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(CONCAT "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(CONCAT "PRO-FP" in_out_t=fp32_t)

# PAD
mlel_tosa_variant(PAD "PRO-INT+PRO-FP" in_out_t=bool_t)
mlel_tosa_variant(PAD "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(PAD "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(PAD "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(PAD "EXT-FP8E4M3" in_out_t=fp8e4m3_t)
mlel_tosa_variant(PAD "EXT-FP8E5M2" in_out_t=fp8e5m2_t)
mlel_tosa_variant(PAD "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(PAD "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(PAD "PRO-FP" in_out_t=fp32_t)

# RESHAPE
mlel_tosa_variant(RESHAPE "PRO-INT+PRO-FP" in_out_t=bool_t)
mlel_tosa_variant(RESHAPE "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(RESHAPE "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(RESHAPE "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(RESHAPE "EXT-FP8E4M3" in_out_t=fp8e4m3_t)
mlel_tosa_variant(RESHAPE "EXT-FP8E5M2" in_out_t=fp8e5m2_t)
mlel_tosa_variant(RESHAPE "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(RESHAPE "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(RESHAPE "PRO-FP" in_out_t=fp32_t)

# REVERSE
mlel_tosa_variant(REVERSE "PRO-INT+PRO-FP" in_out_t=bool_t)
mlel_tosa_variant(REVERSE "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(REVERSE "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(REVERSE "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(REVERSE "EXT-FP8E4M3" in_out_t=fp8e4m3_t)
mlel_tosa_variant(REVERSE "EXT-FP8E5M2" in_out_t=fp8e5m2_t)
mlel_tosa_variant(REVERSE "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(REVERSE "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(REVERSE "PRO-FP" in_out_t=fp32_t)

# SLICE
mlel_tosa_variant(SLICE "PRO-INT+PRO-FP" in_out_t=bool_t)
mlel_tosa_variant(SLICE "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(SLICE "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(SLICE "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(SLICE "EXT-FP8E4M3" in_out_t=fp8e4m3_t)
mlel_tosa_variant(SLICE "EXT-FP8E5M2" in_out_t=fp8e5m2_t)
mlel_tosa_variant(SLICE "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(SLICE "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(SLICE "PRO-FP" in_out_t=fp32_t)

# TILE
mlel_tosa_variant(TILE "PRO-INT+PRO-FP" in_out_t=bool_t)
mlel_tosa_variant(TILE "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(TILE "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(TILE "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(TILE "EXT-FP8E4M3" in_out_t=fp8e4m3_t)
mlel_tosa_variant(TILE "EXT-FP8E5M2" in_out_t=fp8e5m2_t)
mlel_tosa_variant(TILE "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(TILE "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(TILE "PRO-FP" in_out_t=fp32_t)

# TRANSPOSE
mlel_tosa_variant(TRANSPOSE "PRO-INT+PRO-FP" in_out_t=bool_t)
mlel_tosa_variant(TRANSPOSE "PRO-INT" in_out_t=i8_t)
mlel_tosa_variant(TRANSPOSE "PRO-INT" in_out_t=i16_t)
mlel_tosa_variant(TRANSPOSE "PRO-INT" in_out_t=i32_t)
mlel_tosa_variant(TRANSPOSE "EXT-FP8E4M3" in_out_t=fp8e4m3_t)
mlel_tosa_variant(TRANSPOSE "EXT-FP8E5M2" in_out_t=fp8e5m2_t)
mlel_tosa_variant(TRANSPOSE "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(TRANSPOSE "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(TRANSPOSE "PRO-FP" in_out_t=fp32_t)

# GATHER
mlel_tosa_variant(GATHER "PRO-INT" in_out_t=i8_t index_t=i32_t)
mlel_tosa_variant(GATHER "PRO-INT" in_out_t=i16_t index_t=i32_t)
mlel_tosa_variant(GATHER "PRO-INT" in_out_t=i32_t index_t=i32_t)
mlel_tosa_variant(GATHER "EXT-FP8E4M3" in_out_t=fp8e4m3_t index_t=i32_t)
mlel_tosa_variant(GATHER "EXT-FP8E5M2" in_out_t=fp8e5m2_t index_t=i32_t)
mlel_tosa_variant(GATHER "PRO-FP" in_out_t=fp16_t index_t=i32_t)
mlel_tosa_variant(GATHER "EXT-BF16" in_out_t=bf16_t index_t=i32_t)
mlel_tosa_variant(GATHER "PRO-FP" in_out_t=fp32_t index_t=i32_t)

# SCATTER
mlel_tosa_variant(SCATTER "PRO-INT" in_out_t=i8_t index_t=i32_t)
mlel_tosa_variant(SCATTER "PRO-INT" in_out_t=i16_t index_t=i32_t)
mlel_tosa_variant(SCATTER "PRO-INT" in_out_t=i32_t index_t=i32_t)
mlel_tosa_variant(SCATTER "EXT-FP8E4M3" in_out_t=fp8e4m3_t index_t=i32_t)
mlel_tosa_variant(SCATTER "EXT-FP8E5M2" in_out_t=fp8e5m2_t index_t=i32_t)
mlel_tosa_variant(SCATTER "PRO-FP" in_out_t=fp16_t index_t=i32_t)
mlel_tosa_variant(SCATTER "EXT-BF16" in_out_t=bf16_t index_t=i32_t)
mlel_tosa_variant(SCATTER "PRO-FP" in_out_t=fp32_t index_t=i32_t)

# RESIZE
mlel_tosa_variant(RESIZE "PRO-INT" resize_t=i16_t in_t=i8_t out_t=i32_t)
mlel_tosa_variant(RESIZE "PRO-INT" resize_t=i16_t in_t=i8_t out_t=i8_t)
mlel_tosa_variant(RESIZE "EXT-INT16" resize_t=i16_t in_t=i16_t out_t=i48_t)
mlel_tosa_variant(RESIZE "EXT-INT16" resize_t=i16_t in_t=i16_t out_t=i16_t)
mlel_tosa_variant(RESIZE "PRO-FP" resize_t=fp16_t in_t=fp16_t out_t=fp16_t)
mlel_tosa_variant(RESIZE "EXT-BF16" resize_t=bf16_t in_t=bf16_t out_t=bf16_t)
mlel_tosa_variant(RESIZE "PRO-FP" resize_t=fp32_t in_t=fp32_t out_t=fp32_t)

# CAST
mlel_tosa_variant(CAST "PRO-INT" in_t=bool_t out_t=i8_t)
mlel_tosa_variant(CAST "PRO-INT" in_t=bool_t out_t=i16_t)
mlel_tosa_variant(CAST "PRO-INT" in_t=bool_t out_t=i32_t)
mlel_tosa_variant(CAST "PRO-INT" in_t=i8_t out_t=bool_t)
mlel_tosa_variant(CAST "PRO-INT" in_t=i8_t out_t=i16_t)
mlel_tosa_variant(CAST "PRO-INT" in_t=i8_t out_t=i32_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=i8_t out_t=fp16_t)
mlel_tosa_variant(CAST "EXT-BF16" in_t=i8_t out_t=bf16_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=i8_t out_t=fp32_t)
mlel_tosa_variant(CAST "PRO-INT" in_t=i16_t out_t=bool_t)
mlel_tosa_variant(CAST "PRO-INT" in_t=i16_t out_t=i8_t)
mlel_tosa_variant(CAST "PRO-INT" in_t=i16_t out_t=i32_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=i16_t out_t=fp16_t)
mlel_tosa_variant(CAST "EXT-BF16" in_t=i16_t out_t=bf16_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=i16_t out_t=fp32_t)
mlel_tosa_variant(CAST "PRO-INT" in_t=i32_t out_t=bool_t)
mlel_tosa_variant(CAST "PRO-INT" in_t=i32_t out_t=i8_t)
mlel_tosa_variant(CAST "PRO-INT" in_t=i32_t out_t=i16_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=i32_t out_t=fp16_t)
mlel_tosa_variant(CAST "EXT-BF16" in_t=i32_t out_t=bf16_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=i32_t out_t=fp32_t)
mlel_tosa_variant(CAST "EXT-BF16" in_t=bf16_t out_t=i8_t)
mlel_tosa_variant(CAST "EXT-BF16" in_t=bf16_t out_t=i16_t)
mlel_tosa_variant(CAST "EXT-BF16" in_t=bf16_t out_t=i32_t)
mlel_tosa_variant(CAST "EXT-BF16+EXT-FP8E4M3" in_t=bf16_t out_t=fp8e4m3_t)
mlel_tosa_variant(CAST "EXT-BF16+EXT-FP8E5M2" in_t=bf16_t out_t=fp8e5m2_t)
mlel_tosa_variant(CAST "EXT-BF16" in_t=bf16_t out_t=fp32_t)
mlel_tosa_variant(CAST "EXT-FP8E4M3" in_t=fp8e4m3_t out_t=fp16_t)
mlel_tosa_variant(CAST "EXT-BF16+EXT-FP8E4M3" in_t=fp8e4m3_t out_t=bf16_t)
mlel_tosa_variant(CAST "EXT-FP8E4M3" in_t=fp8e4m3_t out_t=fp32_t)
mlel_tosa_variant(CAST "EXT-FP8E5M2" in_t=fp8e5m2_t out_t=fp16_t)
mlel_tosa_variant(CAST "EXT-BF16+EXT-FP8E5M2" in_t=fp8e5m2_t out_t=bf16_t)
mlel_tosa_variant(CAST "EXT-FP8E5M2" in_t=fp8e5m2_t out_t=fp32_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=fp16_t out_t=i8_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=fp16_t out_t=i16_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=fp16_t out_t=i32_t)
mlel_tosa_variant(CAST "EXT-FP8E4M3" in_t=fp16_t out_t=fp8e4m3_t)
mlel_tosa_variant(CAST "EXT-FP8E5M2" in_t=fp16_t out_t=fp8e5m2_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=fp16_t out_t=fp32_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=fp32_t out_t=i8_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=fp32_t out_t=i16_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=fp32_t out_t=i32_t)
mlel_tosa_variant(CAST "EXT-FP8E4M3" in_t=fp32_t out_t=fp8e4m3_t)
mlel_tosa_variant(CAST "EXT-FP8E5M2" in_t=fp32_t out_t=fp8e5m2_t)
mlel_tosa_variant(CAST "EXT-BF16" in_t=fp32_t out_t=bf16_t)
mlel_tosa_variant(CAST "PRO-FP" in_t=fp32_t out_t=fp16_t)

# RESCALE
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i8_t out_t=i8_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i8_t out_t=ui8_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=ui8_t out_t=i8_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i8_t out_t=i8_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i8_t out_t=ui8_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=ui8_t out_t=i8_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i8_t out_t=i16_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i8_t out_t=ui16_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=ui8_t out_t=i16_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i8_t out_t=i16_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i8_t out_t=ui16_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=ui8_t out_t=i16_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i8_t out_t=i32_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i8_t out_t=i32_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i16_t out_t=i8_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i16_t out_t=ui8_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=ui16_t out_t=i8_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i16_t out_t=i8_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i16_t out_t=ui8_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=ui16_t out_t=i8_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i16_t out_t=i16_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i16_t out_t=ui16_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=ui16_t out_t=i16_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i16_t out_t=i16_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i16_t out_t=ui16_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=ui16_t out_t=i16_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i16_t out_t=i32_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i16_t out_t=i32_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i32_t out_t=i8_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i32_t out_t=i8_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i32_t out_t=i16_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i32_t out_t=i16_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i32_t out_t=i32_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "PRO-INT" in_t=i32_t out_t=i32_t mul_t=i32_t)
mlel_tosa_variant(RESCALE "EXT-INT16" in_t=i48_t out_t=i8_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "EXT-INT16" in_t=i48_t out_t=i16_t mul_t=i16_t)
mlel_tosa_variant(RESCALE "EXT-INT16" in_t=i48_t out_t=i32_t mul_t=i16_t)

# CONST
mlel_tosa_variant(CONST "PRO-INT+PRO-FP" out_t=bool_t)
mlel_tosa_variant(CONST "EXT-INT4" out_t=i4_t)
mlel_tosa_variant(CONST "PRO-INT+PRO-FP" out_t=i8_t)
mlel_tosa_variant(CONST "PRO-INT+PRO-FP" out_t=i16_t)
mlel_tosa_variant(CONST "PRO-INT+PRO-FP" out_t=i32_t)
mlel_tosa_variant(CONST "EXT-INT16" out_t=i48_t)
mlel_tosa_variant(CONST "EXT-FP8E4M3" out_t=fp8e4m3_t)
mlel_tosa_variant(CONST "EXT-FP8E5M2" out_t=fp8e5m2_t)
mlel_tosa_variant(CONST "PRO-FP" out_t=fp16_t)
mlel_tosa_variant(CONST "EXT-BF16" out_t=bf16_t)
mlel_tosa_variant(CONST "PRO-FP" out_t=fp32_t)

# IDENTITY
mlel_tosa_variant(IDENTITY "PRO-INT+PRO-FP" in_out_t=bool_t)
mlel_tosa_variant(IDENTITY "EXT-INT4" in_out_t=i4_t)
mlel_tosa_variant(IDENTITY "PRO-INT+PRO-FP" in_out_t=i8_t)
mlel_tosa_variant(IDENTITY "PRO-INT+PRO-FP" in_out_t=i16_t)
mlel_tosa_variant(IDENTITY "PRO-INT+PRO-FP" in_out_t=i32_t)
mlel_tosa_variant(IDENTITY "EXT-INT16" in_out_t=i48_t)
mlel_tosa_variant(IDENTITY "EXT-FP8E4M3" in_out_t=fp8e4m3_t)
mlel_tosa_variant(IDENTITY "EXT-FP8E5M2" in_out_t=fp8e5m2_t)
mlel_tosa_variant(IDENTITY "PRO-FP" in_out_t=fp16_t)
mlel_tosa_variant(IDENTITY "EXT-BF16" in_out_t=bf16_t)
mlel_tosa_variant(IDENTITY "PRO-FP" in_out_t=fp32_t)

# CUSTOM
mlel_tosa_variant(CUSTOM "PRO-INT+PRO-FP")

# COND_IF
mlel_tosa_variant(COND_IF "EXT-CONTROLFLOW")

# WHILE_LOOP
mlel_tosa_variant(WHILE_LOOP "EXT-CONTROLFLOW")

# VARIABLE
mlel_tosa_variant(VARIABLE "PRO-INT" in_t=i8_t)
mlel_tosa_variant(VARIABLE "PRO-FP" in_t=fp16_t)
mlel_tosa_variant(VARIABLE "PRO-FP" in_t=fp32_t)

# VARIABLE_WRITE
mlel_tosa_variant(VARIABLE_WRITE "PRO-INT" in_t=i8_t)
mlel_tosa_variant(VARIABLE_WRITE "PRO-FP" in_t=fp16_t)
mlel_tosa_variant(VARIABLE_WRITE "PRO-FP" in_t=fp32_t)

# VARIABLE_READ
mlel_tosa_variant(VARIABLE_READ "PRO-INT" out_t=i8_t)
mlel_tosa_variant(VARIABLE_READ "PRO-FP" out_t=fp16_t)
mlel_tosa_variant(VARIABLE_READ "PRO-FP" out_t=fp32_t)

# CONST_SHAPE
mlel_tosa_variant(CONST_SHAPE "PRO-INT+PRO-FP")
