# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#

# Shader recipes describe code generation; the imported tables describe legal types.
set(SHADER_ADD elementwise_binary)
set(EXPRESSION_ADD "value1 + value2")
set(SHADER_BITWISE_AND elementwise_binary)
set(EXPRESSION_BITWISE_AND "value1 & value2")
set(SHADER_BITWISE_OR elementwise_binary)
set(EXPRESSION_BITWISE_OR "value1 | value2")
set(SHADER_BITWISE_XOR elementwise_binary)
set(EXPRESSION_BITWISE_XOR "value1 ^ value2")
set(SHADER_INTDIV elementwise_binary)
set(EXPRESSION_INTDIV "value1 / value2")
set(SHADER_LOGICAL_AND elementwise_binary)
set(EXPRESSION_LOGICAL_AND "value1 && value2")
set(SHADER_LOGICAL_LEFT_SHIFT elementwise_binary)
set(EXPRESSION_LOGICAL_LEFT_SHIFT "uint(value1) << uint(value2)")
set(SHADER_LOGICAL_RIGHT_SHIFT elementwise_binary)
set(EXPRESSION_LOGICAL_RIGHT_SHIFT "zeroExtend(value1) >> uint(value2)")
set(SHADER_LOGICAL_OR elementwise_binary)
set(EXPRESSION_LOGICAL_OR "value1 || value2")
set(SHADER_LOGICAL_XOR elementwise_binary)
set(EXPRESSION_LOGICAL_XOR "value1 ^^ value2")
set(SHADER_MAXIMUM elementwise_binary)
set(EXPRESSION_MAXIMUM "applyMax(value1, value2, pushConstants.nanMode)")
set(SHADER_MINIMUM elementwise_binary)
set(EXPRESSION_MINIMUM "applyMin(value1, value2, pushConstants.nanMode)")
set(SHADER_POW elementwise_binary)
set(EXPRESSION_POW "power(value1, value2)")
set(SHADER_SUB elementwise_binary)
set(EXPRESSION_SUB "value1 - value2")
set(SHADER_ABS elementwise_unary)
set(EXPRESSION_ABS "abs(value1)")
set(SHADER_BITWISE_NOT elementwise_unary)
set(EXPRESSION_BITWISE_NOT "~value1")
set(SHADER_CEIL elementwise_unary)
set(EXPRESSION_CEIL "ceil(value1)")
set(SHADER_CLZ elementwise_unary)
set(EXPRESSION_CLZ "clz(value1)")
set(SHADER_COS elementwise_unary)
set(EXPRESSION_COS "cos(value1)")
set(SHADER_EXP elementwise_unary)
set(EXPRESSION_EXP "exp(value1)")
set(SHADER_FLOOR elementwise_unary)
set(EXPRESSION_FLOOR "floor(value1)")
set(SHADER_LOG elementwise_unary)
set(EXPRESSION_LOG "log_guarded(value1)")
set(SHADER_LOGICAL_NOT elementwise_unary)
set(EXPRESSION_LOGICAL_NOT "!value1")
set(SHADER_RECIPROCAL elementwise_unary)
set(EXPRESSION_RECIPROCAL "1.0 / value1")
set(SHADER_RSQRT elementwise_unary)
set(EXPRESSION_RSQRT "inversesqrt(value1)")
set(SHADER_SIN elementwise_unary)
set(EXPRESSION_SIN "sin_hybrid(value1)")
set(SHADER_EQUAL elementwise_binary)
set(EXPRESSION_EQUAL "value1 == value2")
set(SHADER_GREATER elementwise_binary)
set(EXPRESSION_GREATER "value1 > value2")
set(SHADER_GREATER_EQUAL elementwise_binary)
set(EXPRESSION_GREATER_EQUAL "value1 >= value2")
set(SHADER_ERF elementwise_unary)
set(EXPRESSION_ERF "erf(value1)")
set(SHADER_SIGMOID elementwise_unary)
set(EXPRESSION_SIGMOID "1.0 / (1.0 + exp(-value1))")
set(SHADER_TANH elementwise_unary)
set(EXPRESSION_TANH "tanh_clamped(value1)")
set(KEYS_ARGMAX in_t)
set(KEYS_AVG_POOL2D in_out_t acc_t)
set(KEYS_CAST in_t out_t)
set(KEYS_GATHER in_out_t index_t)
set(KEYS_SCATTER in_out_t index_t)
set(KEYS_MATMUL in_t out_t)
set(KEYS_MUL in_t out_t)
set(KEYS_NEGATE in_out_t acc_t)
set(KEYS_RESIZE in_t out_t)
set(KEYS_TABLE in_t out_t)
set(KEYS_RESCALE in_t out_t mul_t)
set(KEYS_FFT2D "")
set(KEYS_RFFT2D "")
set(KEYS_ARITHMETIC_RIGHT_SHIFT in_out_t)
set(KEYS_CLAMP in_out_t)
set(KEYS_CONCAT in_out_t)
set(KEYS_MAX_POOL2D in_out_t)
set(KEYS_PAD in_out_t)
set(KEYS_RESHAPE in_out_t)
set(KEYS_REVERSE in_out_t)
set(KEYS_SELECT in_out_t)
set(KEYS_SLICE in_out_t)
set(KEYS_TILE in_out_t)
set(KEYS_TRANSPOSE in_out_t)

set(INIT_REDUCE_ALL "true")
set(INIT_REDUCE_ANY "false")
set(INIT_REDUCE_MAX "(pushConstants.nanMode == NAN_MODE_IGNORE) ? COMP_T(NAN) : COMP_T(${ESCAPE_CHAR}%in_out_t_lowest${ESCAPE_CHAR}%)")
set(INIT_REDUCE_MIN "(pushConstants.nanMode == NAN_MODE_IGNORE) ? COMP_T(NAN) : COMP_T(${ESCAPE_CHAR}%in_out_t_max${ESCAPE_CHAR}%)")
set(INIT_REDUCE_PRODUCT "1")
set(INIT_REDUCE_SUM "0")
set(EXPRESSION_REDUCE_ALL "result && value")
set(EXPRESSION_REDUCE_ANY "result || value")
set(EXPRESSION_REDUCE_MAX "max(result, value)")
set(EXPRESSION_REDUCE_MIN "min(result, value)")
set(EXPRESSION_REDUCE_PRODUCT "result * value")
set(EXPRESSION_REDUCE_SUM "result + value")

function(mlel_tosa_variant OPERATION PROFILE)
    # These graph/data operations have no separate TOSA compute shader. CONST and
    # IDENTITY use the layer's CAST copy path, including widened i4/i48 storage.
    if(OPERATION MATCHES "^(CUSTOM|COND_IF|WHILE_LOOP|VARIABLE|VARIABLE_READ|VARIABLE_WRITE|CONST_SHAPE)$")
        return()
    endif()
    foreach(PAIR IN LISTS ARGN)
        string(REPLACE "=" ";" PARTS "${PAIR}")
        list(GET PARTS 0 ROLE)
        list(GET PARTS 1 TYPE)
        if(TYPE MATCHES "^i[48]_t$")
            set(TYPE int8_t)
        elseif(TYPE STREQUAL "i16_t")
            set(TYPE int16_t)
        elseif(TYPE STREQUAL "i32_t")
            set(TYPE int)
        elseif(TYPE STREQUAL "i48_t")
            set(TYPE int64_t)
        elseif(TYPE STREQUAL "ui8_t")
            set(TYPE uint8_t)
        elseif(TYPE STREQUAL "ui16_t")
            set(TYPE uint16_t)
        elseif(TYPE STREQUAL "bool_t")
            set(TYPE bool)
        elseif(TYPE STREQUAL "fp16_t")
            set(TYPE float16_t)
        elseif(TYPE STREQUAL "fp32_t")
            set(TYPE float)
        elseif(TYPE STREQUAL "bf16_t")
            set(TYPE bfloat16_t)
        elseif(TYPE STREQUAL "fp8e4m3_t")
            set(TYPE float8_e4m3_t)
        elseif(TYPE STREQUAL "fp8e5m2_t")
            set(TYPE float8_e5m2_t)
        endif()
        set(${ROLE} "${TYPE}")
    endforeach()
    # NEGATE uses FP32 computation for floating-point storage. Widening is exact
    # for negation and matches Negate::createSpirv, including encoded BF16.
    if(OPERATION STREQUAL "NEGATE" AND NOT in_out_t MATCHES "^int")
        set(acc_t float)
    endif()
    set(SPV_FILES "")
    set(TEST_OPERATION "${OPERATION}")
    if(OPERATION STREQUAL "CONST" OR OPERATION STREQUAL "IDENTITY")
        if(OPERATION STREQUAL "CONST")
            set(in_out_t "${out_t}")
        endif()
        set(in_t "${in_out_t}")
        set(out_t "${in_out_t}")
        set(OPERATION CAST)
    endif()
    string(TOLOWER "${OPERATION}" NAME)
    if(OPERATION MATCHES "^(CONV2D|CONV3D|DEPTHWISE_CONV2D|TRANSPOSE_CONV2D)$")
        mlel_spv_convolution(${NAME} ${in_t} ${weight_t} ${out_t} ${acc_t})
        set(SHADER "${NAME}")
        set(KEYS "${in_t};${weight_t};${out_t};${acc_t}")
    elseif(DEFINED SHADER_${OPERATION})
        set(SHADER "${SHADER_${OPERATION}}")
        if(NOT DEFINED in_out_t)
            set(in_out_t "${in_t}")
        endif()
        mlel_spv_elementwise(${SHADER} ${NAME} "${EXPRESSION_${OPERATION}}" ${in_out_t})
        set(KEYS "${OPERATION};${in_out_t}")
        if(SHADER STREQUAL "elementwise_binary")
            if(OPERATION MATCHES "^(EQUAL|GREATER|GREATER_EQUAL)$")
                list(APPEND KEYS bool)
            else()
                list(APPEND KEYS "${in_out_t}")
            endif()
        endif()
    elseif(OPERATION MATCHES "^REDUCE_")
        string(REPLACE "reduce_" "" REDUCTION "${NAME}")
        mlel_spv_reduce(${REDUCTION} "${INIT_${OPERATION}}" "${EXPRESSION_${OPERATION}}" "${in_out_t}")
        set(SHADER reduce)
        set(KEYS "${OPERATION};${in_out_t}")
    elseif(DEFINED KEYS_${OPERATION})
        set(SHADER "${NAME}")
        if(OPERATION STREQUAL "AVG_POOL2D")
            set(SHADER avgpool2d)
        elseif(OPERATION STREQUAL "MAX_POOL2D")
            set(SHADER maxpool2d)
        endif()
        set(TYPES "")
        set(KEYS "")
        foreach(ROLE IN LISTS KEYS_${OPERATION})
            if(NOT DEFINED ${ROLE})
                message(FATAL_ERROR "Missing ${ROLE} in ${OPERATION}: ${ARGN}")
            endif()
            list(APPEND TYPES "${ROLE} ${${ROLE}}")
            list(APPEND KEYS "${${ROLE}}")
        endforeach()
        mlel_spv(${SHADER} ${TYPES})
    else()
        message(FATAL_ERROR "Missing shader recipe for TOSA operator ${OPERATION}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY MLEL_TOSA_SPV_FILES ${SPV_FILES})

    set(KEY_ARGS "")
    set(TEST_NAME "${TEST_OPERATION}_${PROFILE}")
    foreach(KEY IN LISTS KEYS)
        string(APPEND KEY_ARGS "\"${KEY}\", ")
        string(APPEND TEST_NAME "_${KEY}")
    endforeach()
    string(REGEX REPLACE "[^a-zA-Z0-9_]" "_" TEST_NAME "${TEST_NAME}")
    set_property(DIRECTORY APPEND_STRING PROPERTY MLEL_TOSA_SHADER_CASES
        "    {\"${SHADER}\", {${KEY_ARGS}}, \"${TEST_NAME}\"},\n")
endfunction()

include(${CMAKE_CURRENT_LIST_DIR}/tosa_1_0_types.cmake)
get_property(TOSA_SPV_FILES DIRECTORY PROPERTY MLEL_TOSA_SPV_FILES)
list(APPEND SPV_FILES ${TOSA_SPV_FILES})
list(REMOVE_DUPLICATES SPV_FILES)
get_property(TOSA_CASES DIRECTORY PROPERTY MLEL_TOSA_SHADER_CASES)
file(CONFIGURE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/tosa_shader_cases.hpp.inc" CONTENT "${TOSA_CASES}" @ONLY)
